@startuml Diagramme des classes d'utilisation
left to right direction

/' Définition des acteurs humains '/
:Clients: as Client
:Conseillers: as Conseiller
:Administrateurs: as Admin

/' Définition des acteurs systèmes '/
:Système de paiement: as SysPaiement
:Système de vérification d'adresse: as SysAdresse
:Interface d'investissement: as IntInvest
:Système de notification: as SysNotif

/' Définition des cas d'utilisation '/
package "Système de paiement"{
    usecase "Se connecter" as UC0
    usecase "Vérifier le solde" as UC1
    usecase "Effectuer un virement" as UC2
    usecase "Demander un prêt" as UC3
    secase "Consulter les comptes clients" as UC4
    usecase "Approuver un prêt" as UC5
}

package "Investissements" {
    usecase "Consulter portefeuille et performance" as UC_Portefeuille
    usecase "Recevoir conseils selon profil de risque" as UC_Conseils
    usecase "Acheter et/ou vendre une action" as UC_AchatVenteAction
  }

/' Associations entre acteurs et cas d'utilisation '/
:Clients: --> UC1
:Clients: --> UC2
:Clients: --> UC3
UC4 <-- :Conseillers:
UC5 <-- :Conseillers:

@enduml